version: '3.1'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: examplepassword
    networks:
      - my-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - my-network

  express-app:
    build:
      context: ./nodejs  # Specify the context directory for building the image
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - DATABASE_USER=root
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_PASSWORD=examplepassword
      - DATABASE_NAME=my_blogger
    depends_on:
      - db
    networks:
      - my-network


  flask-app:
    build:
      context: ./python  # Specify the context directory for building the image
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - SERVER_PORT=5000
      - DATABASE_USER=root
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_PASSWORD=examplepassword
      - DATABASE_NAME=my_blogger
    depends_on:
      - db
    networks:
      - my-network

  react-app:
    build:
      context: ./react-app  # Specify the context directory for building the image
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    environment:
      - PORT=3001
    depends_on:
      - db
    networks:
      - my-network

networks:
  my-network:

